# Generated by Django 5.1.15 on 2026-09-21 06:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_no', models.CharField(max_length=40)),
                ('packed_at', models.DateTimeField()),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets', to='core.greenhouse')),
            ],
            options={
                'ordering': ['greenhouse_id', 'pallet_no'],
            },
        ),
        migrations.CreateModel(
            name='PalletLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('grade', models.CharField(choices=[('甲', '甲'), ('乙', '乙')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallet_lines', to='core.zone')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.shipmentpallet')),
            ],
            options={
                'ordering': ['pallet_id', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='shipmentpallet',
            constraint=models.UniqueConstraint(fields=('greenhouse', 'pallet_no'), name='uniq_pallet_no_per_greenhouse'),
        ),
    ]
